name: Deploy with GH Actions to set up project with Tailwind

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v4
      - name: Setting up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Building CSS with Tailwind
        run: npm run css:build
      - name: Running ls
        run: ls
      - name: Copying index.html to dist directory
        run: cp ./src/index.html dist/
      - name: Copying images to dist/img directory
        run: cp -r ./src/images dist/images
      - name: Copying JavaScript file
        run: cp ./src/app.js dist/
      - name: Setting up Pages
        uses: actions/configure-pages@v3
      - name: Uploading artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploying to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
